### ISSUE TITLE
Does flammarion run on a MAC?

### ISSUE THREAD

**Issue by joegyoung** [zach-capalbo/flammarion#32]
I am running `ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14] ` on `Mac 10.10.5`. In IRB, I run

```
  require 'flammarion'
  f = Flammarion::Engraving.new
```
Chrome opens with URL `file:///usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/flammarion-0.1.5/lib/html/build/index.html` and reports at the bottom that it is detached. IRB reports timeout error. Further probing shows that the javascript to run websockets is not providing the port number..

I run the same code in windows 7 and it works..

Can you help?

**Comment by zach-capalbo** [comment]
I've never tried running it on a Mac, and don't have access to one. I'll look and see if there's anything that should cause issues, but won't be able to verify any fixes.

**Comment by pkoppstein** [comment]
Flammarion looks great and I have installed it on a Mac OS 10.9.5 with ruby 2.3, but whatever I do, Chrome just comes up with a black screen and the word "Detached" (in faint red) in the lower left-hand corner. The irb console eventually shows a timeout, e.g.

    > Flammarion.about
    Flammarion::SetupError: Timed out while waiting for a connecting using www.
	from /usr/local/lib/ruby/gems/2.3.0/gems/flammarion-0.1.5/lib/flammarion/revelator.rb:52:in `rescue in wait_for_a_connection'
	from /usr/local/lib/ruby/gems/2.3.0/gems/flammarion-0.1.5/lib/flammarion/revelator.rb:50:in `wait_for_a_connection'
	from /usr/local/lib/ruby/gems/2.3.0/gems/flammarion-0.1.5/lib/flammarion/engraving.rb:48:in `initialize'
	from /usr/local/lib/ruby/gems/2.3.0/gems/flammarion-0.1.5/lib/flammarion/about.rb:4:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/flammarion-0.1.5/lib/flammarion/about.rb:4:in `about'
	from (irb):2

**Comment by zach-capalbo** [comment]
Hmm... Would one of you with a Mac mind running the following ruby script, and letting me know what comes up?

```ruby
require 'launchy'
Launchy.open("https://peaceful-escarpment-7112.herokuapp.com/echo.html?test=hello World&abc=123".gsub(/\s/, "%20"))
```

Thanks!

**Comment by pkoppstein** [comment]
@zach-capalbo - I got:

    test: hello%20World
    abc: 123

**Comment by obromios** [comment]
I am having the same problem as joegyoung on a Mac

**Comment by zach-capalbo** [comment]
Should work now with version >= 0.1.9
