### ISSUE TITLE
Use better webview

### ISSUE THREAD

**Issue by xiejiangzhi** [zach-capalbo/flammarion#42]
When we use browser to render the page, if I close my browser, the app will be closed。and many settings of browser will affect our app.

I have wrapped a [webview](https://github.com/xiejiangzhi/webview), it based on [zserge/webview](https://github.com/zserge/webview). I think it is better.

**Comment by zach-capalbo** [comment]
Thanks for sharing! That's a great idea! It should be pretty easy to build a new `Revelator` (i.e., Flammarion display backend) that uses your webview. I will try it out as soon as I can, or feel free to submit a pull request if you'd like to do it yourself

**Comment by xiejiangzhi** [comment]
I am developing my own application, so there is currently no time to create a PR.
My application also based on WebView, it don't like this repo, I directly use HTML + JS + CSS to build page. For me it's easier. But this repo let me know how to write app based on WebView. thanks
